### ISSUE TITLE
[1.16.5 Server] crash on startup, cannot guarantee SoundEvent.ResourceLocation is available at a specific time on forge loading

### ISSUE THREAD

**Issue by NighthowlerStudios** [Tfarcenim/HitmarkerForge#1]
https://pastebin.com/TdVW0m9X

crash occurs if a server has a lower end cpu that allows the registry threads to race

**Comment by NighthowlerStudios** [comment]
https://github.com/Tfarcenim/Hitmarker/issues/1

**Comment by Tfarcenim** [comment]
fixed in 1.2
