### ISSUE TITLE
[1.16.5 Backport Request] Red marker recolour and kill sound reimplementation

### ISSUE THREAD

**Issue by NighthowlerStudios** [Tfarcenim/HitmarkerForge#2]
The red hit marker nor any kill sounds are present on previous versions of the mod, for example 1.16.5.  This issue just requests that it be backported to those versions considering how simple implementation would be.

**Comment by NighthowlerStudios** [comment]
I've actually found that the hitmarker is changing colour, but by shader error it is changing its colour to cyan and acting transparent, rather than turning red.  This might be a shader issue or an incompatibility with Optifine, but I doubt it as the normal white colour renders fine.

Sounds, however, are definitely entirely missing.

**Comment by Tfarcenim** [comment]
fixed in 1.2
